### ISSUE TITLE
Signup Page - Scaling/Adaptive Issue #CSS

### ISSUE THREAD

**Issue by geekwise** [geekwise/GroupGist#14]

**Comment by geekwise** [comment]
@EricPSC 
- remove all VH / VW from the CSS and use REM for adaptive states
- Use @MediaQuery for responsive states.

Lets focus on just 4 states for media queries for now.
1: Desktop Full
2: Desktop Half Screen
3: Phone Portrait
4: Phone Landscape

**Comment by spartanadvent** [comment]
this has been taken care of !

**Comment by geekwise** [comment]
@EricPSC - completed
