### ISSUE TITLE
Signup Form Does Not Have A Underline Or Hover State

### ISSUE THREAD

**Issue by geekwise** [geekwise/GroupGist#2]
## @Vinson

![signup](http://i.imgur.com/kqWFOBb.png)

**Comment by spartanadvent** [comment]
@EricPSC 
#12 
taken care of both issues at this time

**Comment by geekwisevinson** [comment]
https://app.moqups.com/vinsonfernandez27@gmail.com/ZzT9oXipaa/edit/page/a423d255a
