### ISSUE TITLE
Javascript - markup.js - loading html externally with regex to store in variable

### ISSUE THREAD

**Issue by geekwise** [geekwise/GroupGist#38]
![](http://i.imgur.com/RJSJIfz.png)

**Comment by geekwise** [comment]
![](http://i.imgur.com/T5fYEOW.png)

**Comment by geekwise** [comment]
Using HTML Comments  to search for what sections to import and save to a variable

**Comment by geekwisevinson** [comment]
@vinferno done loading with XMLHttpRequest
